### ISSUE TITLE
Error while setting up environment on Windows 10

### ISSUE THREAD

**Issue by Kshitij09** [OperationCode/resources_api#235]
Running `make setup` on Windows 10 as per the [Getting Started](https://github.com/OperationCode/resources_api#getting-started) instructions lead to following error -
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
ModuleNotFoundError: No module named 'run'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 556, in list_commands
    rv.update(info.load_app().cli.list_commands(ctx))
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 250, in locate_app
    raise NoAppException('Could not import "{name}".'.format(name=module_name))
flask.cli.NoAppException: Could not import "run".
```

**Comment by aaron-suarez** [comment]
Hmm, this is odd. Just to clarify, you followed all of the steps in the `Getting Started` instructions before encountering this?

**Comment by aaron-suarez** [comment]
@Kshitij09 Can you please provide the versions of Docker and Make that you were running when you encountered this?

**Comment by Kshitij09** [comment]
> Hmm, this is odd. Just to clarify, you followed all of the steps in the `Getting Started` instructions before encountering this?

Yes I followed every instruction and still got this error.




> @Kshitij09 Can you please provide the versions of Docker and Make that you were running when you encountered this?

My system configuration is

Windows 10 Home (64-bit)
Docker: 19.03.1, build 74b1e89e8a
Make: 3.81

**Comment by thinkingserious** [comment]
Hi @Kshitij09,

I was just now able to complete the `make setup` step on my Windows 10 machine.

Perhaps you need to update your Docker to the latest version.

My system configuration is:
Windows 10, version 1903
Docker: 19.03.4
Make: 3.81

With best regards,

Elmer

**Comment by Kshitij09** [comment]
I'm using Latest release of Docker Toolbox and the [Toolbox Releases](https://github.com/docker/toolbox/releases) shows that it has Docker 19.03.1. Is it possible to update this Docker version? Please help me in this regard.

**Comment by aaron-suarez** [comment]
Oh, interesting, looks like Docker Toolbox is a few versions behind on docker?

**Comment by thinkingserious** [comment]
@Kshitij09,

It looks like Docker [recommends|https://forums.docker.com/t/docker-for-windows-or-docker-toolbox/30387/2] [Docker desktop|https://www.docker.com/products/docker-desktop]. Could you please try uninstalling the Docker Toolbox and install Docker Desktop instead? I'm not sure if this will solve this particular issue, but it seems worth a try.

**Comment by Kshitij09** [comment]
I don't meet the minimum system requirements for Docker Desktop. Hence forced to use the toolbox.

**Comment by thinkingserious** [comment]
@Kshitij09,

How about running Docker in a Linux based VM [like so](https://medium.com/@mbyfieldcameron/docker-on-windows-10-home-edition-c186c538dff3)?

**Comment by aaron-suarez** [comment]
@Kshitij09 Are you still having trouble getting set up?

**Comment by Kshitij09** [comment]
@aaron-suarez on Windows 10 - yes. Will try on Ubuntu and let you know. Should I change the title to error while setting up on Docker toolbox?

**Comment by aaron-suarez** [comment]
@Kshitij09 Did you ever get it working on Ubuntu?

And yes, you can change the title if you like. I don't think I've heard of anyone else running into this issue but we can leave it open until someone can reproduce.
