### ISSUE TITLE
500 error when sending a string "false" instead of a boolean

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/resources_api#305]
When `POST`ing a new resource, if you have an otherwise valid resource but include `"paid": "false"` instead of `"paid":false` you get a 500 response. We should either convert the string to a boolean (so `"paid":"false"` would act the same as `"paid":false`) or we should return a 422 error response indicating that this field must be a boolean.

Personally, I'm a big fan of converting it to a boolean for the user, but we need to make sure that only the strings `"true"` and `"false"` (case-insensitive) are accepted, and that `"false"` gets converted to boolean `False`.

Example Payload `POST /api/v1/resources`:
```json
[
    {
        "name": "How To Think Like A Programmer",
        "paid": "False",
        "category": "Getting Started",
        "url":"https://www.youtube.com/watch?v=azcrPFhaY9k",
        "notes": "Learning to program is hard because programming feels different than other skills. But programming isn't about the languages - it is about the way one should think."
    }
]
```

Stacktrace:
```
2020-05-06 19:42:31,709 ERROR (builtins.TypeError) Not a boolean value: 'False'
[SQL: INSERT INTO resource (last_updated, name, url, category_id, paid, notes, upvotes, downvotes, times_clicked) VALUES (%(last_updated)s, %(name)s, %(url)s, %(category_id)s, %(paid)s, %(notes)s, %(upvotes)s, %(downvotes)s, %(times_clicked)s) RETURNING resource.id]
[parameters: [{'name': 'How To Think Like A Programmer', 'notes': "Learning to program is hard because programming feels different than other skills. But programmi ... (32 characters truncated) ... t is about the way one should think.", 'url': 'https://www.youtube.com/watch?v=azcrPFhaY9k', 'category_id': 3, 'paid': 'False', 'last_updated': None}]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1175, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 862, in _init_compiled
    for key in compiled_params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 862, in <genexpr>
    for key in compiled_params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1826, in process
    value = _strict_as_bool(value)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1801, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
TypeError: Not a boolean value: 'False'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/app/api/routes/resource_creation.py", line 57, in create_resources
    db.session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1175, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 862, in _init_compiled
    for key in compiled_params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 862, in <genexpr>
    for key in compiled_params
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1826, in process
    value = _strict_as_bool(value)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1801, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
sqlalchemy.exc.StatementError: (builtins.TypeError) Not a boolean value: 'False'
[SQL: INSERT INTO resource (last_updated, name, url, category_id, paid, notes, upvotes, downvotes, times_clicked) VALUES (%(last_updated)s, %(name)s, %(url)s, %(category_id)s, %(paid)s, %(notes)s, %(upvotes)s, %(downvotes)s, %(times_clicked)s) RETURNING resource.id]
[parameters: [{'name': 'How To Think Like A Programmer', 'notes': "Learning to program is hard because programming feels different than other skills. But programmi ... (32 characters truncated) ... t is about the way one should think.", 'url': 'https://www.youtube.com/watch?v=azcrPFhaY9k', 'category_id': 3, 'paid': 'False', 'last_updated': None}]]
172.20.0.1 - - [06/May/2020 19:42:31] "POST /api/v1/resources HTTP/1.1" 500 -
```

**Comment by jamesfitzer** [comment]
So, validations.py is already taking care of HALF the problem. If you put anything in that field other than a permutation of "true" or "false" with different cases, it bombs out with a 422.

`if col_type is bool:
                if type(field) is str and field.lower() in ["false", "true"]:
                    continue`

The problem comes when setting the value. I have a fix I'm about to check in.

**Comment by jamesfitzer** [comment]
#306 to fix this
